### ISSUE TITLE
Error en make start-dev

### ISSUE THREAD

**Issue by eamanu** [PyAr/asoc_members#149]
Luego de hacer un `make build-dev`, cuando hago `make start-dev` me salta este error:

```
eamanu@eamanu:~/dev/asoc_members$ make start-dev
docker-compose up -d
Creating network "asoc_members_default" with the default driver
Creating volume "asoc_members_pgdata" with default driver
Pulling postgres (postgres:latest)...
latest: Pulling from library/postgres
000eee12ec04: Pull complete
7b8ef50e8d64: Pull complete
304f7c67e7db: Pull complete
9fe4298c8c65: Pull complete
f1ca857656d1: Pull complete
95d6c34812f7: Pull complete
9436c546bd1d: Pull complete
922326a079d9: Pull complete
d6e9dcf0d140: Pull complete
83ac3914c283: Pull complete
5ffbf9359c6e: Pull complete
d280abe82126: Pull complete
f5a37695fe7e: Pull complete
233830cd10db: Pull complete
Digest: sha256:c4da9c62c26179440d5dc7409cb7db60f4a498f0f2c080b97fdb9f7ec0b3502b
Status: Downloaded newer image for postgres:latest
Pulling mail (mailhog/mailhog:)...
latest: Pulling from mailhog/mailhog
d6a5679aa3cf: Pull complete
a1300bbb94d5: Pull complete
0f03c49950cb: Pull complete
b96c5d9bff5f: Pull complete
Digest: sha256:98c7e2e6621c897ad86f31610d756d76b8ee622c354c28a76f4ed49fb6ed996f
Status: Downloaded newer image for mailhog/mailhog:latest
Creating asoc_members_postgres_1 ... done
Creating asoc_members_web_1      ... done
Creating asoc_members_mail_1     ... done
docker-compose exec web ./manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is starting up


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 79, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 207, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  the database system is starting up

Makefile:25: recipe for target 'start-dev' failed
make: *** [start-dev] Error 1
```

Si lo ejecuto una segunda vez, funciona correctamente:

```
eamanu@eamanu:~/dev/asoc_members$ make start-dev
docker-compose up -d
asoc_members_postgres_1 is up-to-date
asoc_members_web_1 is up-to-date
asoc_members_mail_1 is up-to-date
docker-compose exec web ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, events, members, reversion, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying events.0001_initial... OK
  Applying events.0002_auto_20190604_1630... OK
  Applying events.0003_organizer_group_and_perms... OK
  Applying events.0004_auto_20190618_1853... OK
  Applying events.0005_auto_20190715_1440... OK
  Applying events.0006_update_group_and_perms... OK
  Applying events.0007_auto_20191015_2145... OK
  Applying events.0008_auto_20191109_1454... OK
  Applying members.0001_initial... OK
  Applying members.0002_auto_20180430_2303... OK
  Applying members.0003_auto_20180430_1757... OK
  Applying members.0004_auto_20180501_0247... OK
  Applying members.0005_auto_20180501_0509... OK
  Applying members.0006_auto_20180707_1617... OK
  Applying members.0007_auto_20180707_1619... OK
  Applying members.0008_auto_20180708_1538... OK
  Applying members.0009_auto_20180711_2149... OK
  Applying members.0010_auto_20180711_2158... OK
  Applying members.0011_auto_20180714_1912... OK
  Applying members.0012_auto_20180721_1242... OK
  Applying members.0013_auto_20180723_2237... OK
  Applying members.0014_auto_20180726_0007... OK
  Applying members.0015_auto_20180726_0013... OK
  Applying members.0016_auto_20180804_2237... OK
  Applying members.0017_member_shutdown_date... OK
  Applying members.0018_auto_20190112_2303... OK
  Applying members.0019_auto_20190127_2007... OK
  Applying members.0020_auto_20190209_1148... OK
  Applying members.0021_auto_20190313_2109... OK
  Applying members.0022_payment_invoice_ok... OK
  Applying members.0023_auto_20190407_1624... OK
  Applying members.0024_auto_20191208_1231... OK
  Applying reversion.0001_squashed_0004_auto_20160611_1202... OK
  Applying sessions.0001_initial... OK
docker-compose exec web ./manage.py runserver 0.0.0.0:8000
django-configurations version 2.0, using configuration 'Dev'
Performing system checks...

System check identified no issues (0 silenced).
December 22, 2019 - 21:43:32
Django version 2.0.12, using settings 'website.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
```

**Comment by eduzen** [comment]
Hola @eamanu, lo que te está pasando es que el container de django se levanta mucho mas rapido que el container de la base de datos. Fijate que el error dice `the database system is starting up`. Lo que podes hacer la proxima es inicializar primero la db, con un `docker-compose up -d postgres`

Hay muchas alternativas para implementar este "healthcheck"
